Models/Dog.cs
using System.ComponentModel.DataAnnotations;

namespace Dogs.Models
{
    public class Dog
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Введите название породы!")]
        [MaxLength(50)]
        [Display(Name ="Название породы")]
        
        public string Breed { get; set; }
        [Required(ErrorMessage = "Введите название породы по-английски!")]
        [MaxLength(50)]
        [Display(Name = "Название породы по-английски")]
        public string BreedInEnglish { get; set; }
        [Required(ErrorMessage = "Введите происхождение породы!")]
        [MaxLength(30)]
        [Display(Name = "Происхождение породы")]
        public string Origin { get; set;}
        [Required(ErrorMessage = "Введите группу FCI!")]
        [MaxLength(2)]
        [Display(Name = "Группа FCI")]
        public string FCIGroup { get; set; }
        [Required]
        [Display(Name = "Ссылка на картинку")]
        public string ImageUrl { get; set; }
        [Display(Name = "Описание поведения и характера")]
        public string BehaviorCharacter { get; set; }

    }
}

Models/DogDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Dogs.Models
{
    public class DogDbContext:DbContext
    {
        public DogDbContext(DbContextOptions options) : base(options) 
        {
        
        }
        public DbSet<Dog>Dogs { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Dogs.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DogController.cs
using Dogs.Models;
using Microsoft.AspNetCore.Mvc;

namespace Dogs.Controllers
{
    public class DogController:Controller
    {
        private readonly DogDbContext dogDbContext;

        public DogController(DogDbContext dogDbContext) 
        {
            this.dogDbContext = dogDbContext;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        public IActionResult Index()
        {
            var dogs=dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI1()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI2()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI3()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI4()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI5()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI6()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI7()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI8()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI9()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI10()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        public IActionResult FCI0()
        {
            var dogs = dogDbContext.Dogs;
            return View(dogs);
        }
        [HttpPost]
        public async Task<IActionResult> Add(Dog dog)
        {
            if(ModelState.IsValid)
            {
                TempData["status"] = "Добавлена новая порода!";
                await dogDbContext.Dogs.AddAsync(dog);
                await dogDbContext.SaveChangesAsync();  
                return RedirectToAction("Add");
            }
            return View(dog);
            
        }
        public IActionResult Edit()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Dogs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Dogs.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Dog/Add.cshtml
@model Dog
@{
    ViewData["Title"] = "Add";
}
@if (TempData.ContainsKey("status"))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Великолепно!</strong> @TempData["status"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<h1>Добавьте породу</h1>

<div class="row" >
    <div class="col-6">
        <form asp-controller="Dog" asp-action="Add" method="post">
            <div class="form-group">
                <label asp-for="Breed"></label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BreedInEnglish"></label>
                <input asp-for="BreedInEnglish" class="form-control" />
                <span asp-validation-for="BreedInEnglish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FCIGroup"></label>
                <select asp-for="FCIGroup" class="form-control">
                    <option value="1">FCI 1</option>
                    <option value="2">FCI 2</option>
                    <option value="3">FCI 3</option>
                    <option value="4">FCI 4</option>
                    <option value="5">FCI 5</option>
                    <option value="6">FCI 6</option>
                    <option value="7">FCI 7</option>
                    <option value="8">FCI 8</option>
                    <option value="9">FCI 9</option>
                    <option value="10">FCI 10</option>
                    <option value="0">Непризнанные FCI</option>
                </select>                
            </div> 
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BehaviorCharacter"></label>
                <textarea asp-for="BehaviorCharacter" class="form-control" rows="10"></textarea>
                <span asp-validation-for="BehaviorCharacter" class="text-danger"></span>
            </div>
            <button class="btn btn-outline-primary w-25 mt-2">Add</button>
        </form>
    </div>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Views/Dog/FCI0.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI0";
}

<h1>Группа Непризнанные FCI </h1>
<p>
</p>
<h1>Все Непризнанные породы FCI</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "0")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI1.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI1";
}

<h1>Группа FCI 1 - Пастушьи и скотогонные собаки</h1>
<p>
    Породы этой группы, как следует из названия, выведены из пастушьих собак. 
    Эти «пастухи» использовались как для охраны домашних животных и ферм, 
    так и для управления стадами и гуртами скота. Овчарки первой группы 
    веками приучались работать в тесном контакте с человеком. Поэтому из 
    них получаются прекрасные служебные и спортивные собаки, так как 
    склонность к послушанию, выносливость и работоспособность закреплены отбором. 
    В то же время, эти собаки часто недоверчивы к посторонним, активны и требуют 
    воспитания. Из них получаются прекрасные компаньоны, но они больше подходят 
    для активного человека. Несмотря на присущие многим представителям этой группы
    сторожевые качества, они не склонны к доминированию. Для группы типичен шерстный 
    покров средней длины (жесткошерстные и длинношерстные породы в этой группе редки), 
    эти собаки жизнестойки, неприхотливы и легко приспосабливаются к любому климату.
    Могут жить как в городской квартире, так и круглый год на открытом воздухе.
    Размер - от среднего до крупного. Самые известные представители группы - немецкая и 
    шотландская (колли) овчарки.
</p>
<h1>Все породы FCI Group 1</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "1")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI10.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI10";
}

<h1>Группа FCI 10 - Борзые</h1>
<p>
    Это - самые быстрые собаки на Земле, их задача - поймать убегающего зверя. 
    Своенравные, с большим чувством собственного достоинства, но вместе с тем 
    необычайно интеллигентные и импозантные собаки. Требуют продолжительных прогулок.
    С борзыми можно заниматься собачьими бегами. Требуют мягкого и тактичного воспитания.
    Размер - от малого до гигантского. В группе есть породы со всеми типами шерстного покрова.
</p>
<h1>Все породы FCI Group 10</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "10")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI2.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI2";
}

<h1>Группа FCI 2 - </h1>
<p>
</p>
<h1>Все породы FCI Group 2</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "2")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI3.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI3";
}

<h1>Группа FCI 3 - Терьеры</h1>
<p>Терье́ры (англ. terrier из фр. chien terrier — «норная собака», 
    и фр. terrier — «нора, логово» (в современном языке означает 
    также и породу собак) от фр. terre и лат. terra — «земля») — 
    группа пород собак, предназначенных для охоты на норных животных
    и борьбы с грызунами[1][2]. Терьеры — это собаки любой из многих 
    пород или аборигенных пород типа терьера, которые, как правило, 
    маленькие, жилистые, ловкие и отважные[3]. Породы терьеров сильно 
    различаются по размеру от 1 кг (2 фунта) до 32 кг (71 фунт) и обычно 
    классифицируются по параметрам или особенностям. Существует пять 
    различных групп терьеров, каждая из которых имеет разные формы и размеры.</p>
<h1>Все породы FCI Group 3</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if(item.FCIGroup=="3")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
            
        }
    }

</div>

Views/Dog/FCI4.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI4";
}

<h1>Группа FCI 4 - Таксы</h1>
<p>
    Та́кса (нем. Dachshund, dackel) — порода южно-немецких норных охотничьих собак.
    Существует несколько разновидностей такс, отличающихся размерами и весом — 
    стандартные, миниатюрные и кроличьи. Также такс разделяют по шёрстному 
    покрову на гладкошерстных, длинношёрстных и жесткошёрстных.Таксы имеют 
    множество окрасов. Наиболее распространены чёрно-подпалый, рыжий, коричнево-подпалый,
    мраморный (чёрный и коричневый мрамор). Встречаются таксы тигрового и чёрного 
    с тигровыми подпалинами окрасов, последний на данный момент является не признанным 
    FCI окрасом такс. У жесткошёрстных видов очень распространен кабаний окрас 
    (в других разновидностях он не признан). В последнее время в России 
    стал встречаться кремовый (палевый) окрас у длинношёрстных разновидностей, 
    но он не признан FCI. Работа с этим окрасом ведется в рамках UCI.
</p>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "4")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI5.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI5";
}

<h1>Группа FCI 5 - </h1>
<p>
</p>
<h1>Все породы FCI Group 5</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "5")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI6.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI6";
}

<h1>Группа FCI 6 - </h1>
<p>
</p>
<h1>Все породы FCI Group 6</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "6")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI7.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI7";
}

<h1>Группа FCI 7 - </h1>
<p>
</p>
<h1>Все породы FCI Group 7</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "7")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI8.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI8";
}

<h1>Группа FCI 8 - </h1>
<p>
</p>
<h1>Все породы FCI Group 8</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "8")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/FCI9.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "FCI9";
}

<h1>Группа FCI 9 - </h1>
<p>
</p>
<h1>Все породы FCI Group 9</h1>
<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            @if (item.FCIGroup == "9")
            {
                <partial name="_DogCardPartial" model="@item"></partial>
            }
        }
    }

</div>

Views/Dog/Index.cshtml
@model IEnumerable<Dog>
@{
    ViewData["Title"] = "Home Page";
}
<h1>Все породы</h1>
<div class="row">
    @if(Model!=null&&Model.Count()>0)
    {
        @foreach (var item in Model)
        {
            <partial name="_DogCardPartial" model="@item"></partial>
        }
    }
    
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_DogCardPartial.cshtml
@model Dog

<div class="card col-4" style="width: 18rem;">
    <img src="@Model.ImageUrl" class="card-img-top" alt="...">
    <div class="card-body">
        <h4 class="card-title text-center">@Model.Breed</h4>
        <h6 class="text-muted text-center fst-italic">@Model.BreedInEnglish</h6>
        <p class="text-center">Группа FCI: @Model.FCIGroup</p>
        <p class="fw-bolder text-center">@Model.Origin</p>
        <p class="card-text">@Model.BehaviorCharacter</p>
        <a href="#" class="btn btn-info">Подробнее</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dogs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Dogs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dogs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="Index">Все породы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="Add">Добавление породы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI1">FCI 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI2">FCI 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI3">FCI 3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI4">FCI 4</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI5">FCI 5</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI6">FCI 6</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI7">FCI 7</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI8">FCI 8</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI9">FCI 9</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI10">FCI 10</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="FCI0">Непризнанные FCI</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Dogs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>